services:
  #  interviews-service, api-gateway, naming-server, spring-cloud-config, postgres, zipkin, prometheus, grafana

  interviews-service:
    image: bhargavivennam/interviews-service # replace with your image name ex: ${IMAGE_NAME}/interviews-service
    ports:
      - "8081:8081"
    networks:
      - consulting_firm_network
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      MANAGEMENT.ZIPKIN.TRACING.ENDPOINT: http://zipkin-server:9411/api/v2/spans
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/$POSTGRES_DB
      SPRING_DATASOURCE_USERNAME: $POSTGRES_USER
      SPRING_DATASOURCE_PASSWORD: $POSTGRES_PASSWORD

  common-excel-service:
    image: bhargavivennam/common-excel-service
    ports:
      - "8083:8083"
    networks:
      - consulting_firm_network

  app-naming-server:
    image: bhargavivennam/naming-server
    ports:
      - "8761:8761"
    networks:
      - consulting_firm_network

  app-spring-boot-admin:
    image: bhargavivennam/app-spring-boot-admin
    ports:
      - "8082:8082"
    networks:
      - consulting_firm_network

  app-cloud-config-server:
    image: bhargavivennam/app-cloud-config-server
    ports:
      - "8888:8888"
    networks:
      - consulting_firm_network

  zipkin-server:
    image: openzipkin/zipkin:2.23.8
    ports:
      - "9411:9411"
    networks:
      - consulting_firm_network
    restart: always #Restart if there is a problem starting up

  prometheus:
    image: linuxtips/prometheus_alpine
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: always

  grafana:
    image: grafana/grafana:9.3.6
    ports:
      - '3001:3000'
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: always

volumes:
  postgres_data:
    driver: local
  grafana_data:
    driver: local

networks:
  consulting_firm_network:
    driver: bridge